// Mock evidence data lifted from QuantLab desktop semantics:
// run_id / mode / metrics / verdict / lineage / corridor.
// No fake markets — only operator-meaningful fields.

const RUNS = [
  {
    id: "wf_2026-05-09_btc-mr_03",
    mode: "walkforward",
    strategy: "mean-reversion-v3",
    universe: "BTC/USDT · 4h",
    started: "2026-05-09 14:22",
    duration: "00:48:11",
    total_return: 0.187,
    sharpe: 1.82,
    max_drawdown: -0.092,
    trades: 184,
    verdict: "pass",
    candidate: true,
    shortlisted: true,
    baseline: false,
    artifacts: 14,
    commit: "a91f3c2",
  },
  {
    id: "bt_2026-05-09_eth-mom_01",
    mode: "backtest",
    strategy: "momentum-cross-v2",
    universe: "ETH/USDT · 1h",
    started: "2026-05-09 11:05",
    duration: "00:12:04",
    total_return: 0.241,
    sharpe: 1.47,
    max_drawdown: -0.151,
    trades: 422,
    verdict: "review",
    candidate: true,
    shortlisted: false,
    baseline: false,
    artifacts: 9,
    commit: "a91f3c2",
  },
  {
    id: "wf_2026-05-08_btc-mr_02",
    mode: "walkforward",
    strategy: "mean-reversion-v3",
    universe: "BTC/USDT · 4h",
    started: "2026-05-08 19:40",
    duration: "00:46:55",
    total_return: 0.162,
    sharpe: 1.71,
    max_drawdown: -0.104,
    trades: 178,
    verdict: "pass",
    candidate: true,
    shortlisted: true,
    baseline: true,
    artifacts: 14,
    commit: "8e23a04",
  },
  {
    id: "bt_2026-05-08_sol-brk_04",
    mode: "backtest",
    strategy: "breakout-atr-v1",
    universe: "SOL/USDT · 15m",
    started: "2026-05-08 16:12",
    duration: "00:08:22",
    total_return: -0.034,
    sharpe: -0.21,
    max_drawdown: -0.218,
    trades: 612,
    verdict: "fail",
    candidate: false,
    shortlisted: false,
    baseline: false,
    artifacts: 8,
    commit: "8e23a04",
  },
  {
    id: "wf_2026-05-07_btc-mr_01",
    mode: "walkforward",
    strategy: "mean-reversion-v3",
    universe: "BTC/USDT · 4h",
    started: "2026-05-07 22:18",
    duration: "00:51:03",
    total_return: 0.143,
    sharpe: 1.58,
    max_drawdown: -0.117,
    trades: 169,
    verdict: "pass",
    candidate: true,
    shortlisted: false,
    baseline: false,
    artifacts: 14,
    commit: "8e23a04",
  },
  {
    id: "bt_2026-05-07_eth-mom_03",
    mode: "backtest",
    strategy: "momentum-cross-v2",
    universe: "ETH/USDT · 1h",
    started: "2026-05-07 12:40",
    duration: "00:11:48",
    total_return: 0.198,
    sharpe: 1.29,
    max_drawdown: -0.176,
    trades: 401,
    verdict: "review",
    candidate: false,
    shortlisted: false,
    baseline: false,
    artifacts: 9,
    commit: "5d11b87",
  },
  {
    id: "wf_2026-05-06_btc-mr_00",
    mode: "walkforward",
    strategy: "mean-reversion-v2",
    universe: "BTC/USDT · 4h",
    started: "2026-05-06 18:55",
    duration: "00:44:30",
    total_return: 0.118,
    sharpe: 1.36,
    max_drawdown: -0.128,
    trades: 162,
    verdict: "review",
    candidate: false,
    shortlisted: false,
    baseline: false,
    artifacts: 12,
    commit: "5d11b87",
  },
  {
    id: "bt_2026-05-06_sol-brk_03",
    mode: "backtest",
    strategy: "breakout-atr-v1",
    universe: "SOL/USDT · 15m",
    started: "2026-05-06 14:02",
    duration: "00:09:15",
    total_return: 0.071,
    sharpe: 0.84,
    max_drawdown: -0.139,
    trades: 588,
    verdict: "fail",
    candidate: false,
    shortlisted: false,
    baseline: false,
    artifacts: 8,
    commit: "5d11b87",
  },
];

const ARTIFACTS = [
  { name: "config.resolved.yaml",     kind: "config",  size: "4.1 KB",  required: true },
  { name: "trades.parquet",           kind: "data",    size: "812 KB",  required: true },
  { name: "equity_curve.parquet",     kind: "data",    size: "192 KB",  required: true },
  { name: "metrics.json",             kind: "metrics", size: "2.4 KB",  required: true },
  { name: "robustness_verdict.json",  kind: "verdict", size: "1.1 KB",  required: true },
  { name: "walkforward_folds.json",   kind: "data",    size: "18 KB",   required: true },
  { name: "stress_summary.json",      kind: "metrics", size: "3.2 KB",  required: false },
  { name: "run_manifest.json",        kind: "config",  size: "1.8 KB",  required: true },
  { name: "stdout.log",               kind: "log",     size: "44 KB",   required: false },
  { name: "stderr.log",               kind: "log",     size: "1.2 KB",  required: false },
];

const CONFIG_DELTAS = [
  ["strategy.lookback",          ["48", "48", "32"]],
  ["strategy.z_threshold",       ["1.8", "2.0", "1.6"]],
  ["execution.slippage_bps",     ["3", "3", "5"]],
  ["risk.max_position_pct",      ["0.15", "0.20", "0.15"]],
  ["walkforward.train_window_d", ["180", "180", "120"]],
];

const PAPER_SESSIONS = [
  { id: "ps_btc-mr_2026-05-09", strategy: "mean-reversion-v3", universe: "BTC/USDT", state: "running",   pnl: 0.021, orders: 14, alerts: 0 },
  { id: "ps_eth-mom_2026-05-09", strategy: "momentum-cross-v2", universe: "ETH/USDT", state: "running",   pnl: -0.004, orders: 22, alerts: 1 },
  { id: "ps_btc-mr_2026-05-08", strategy: "mean-reversion-v3", universe: "BTC/USDT", state: "stopped",   pnl: 0.014, orders: 11, alerts: 0 },
];

const CORRIDOR = {
  root_alert: "ok",
  sessions: 3,
  latest_order: "filled",
  latest_submit: "signed",
  reachability: "ok",
  last_check: "12s ago",
};

window.__QL_DATA = { RUNS, ARTIFACTS, CONFIG_DELTAS, PAPER_SESSIONS, CORRIDOR };
